### ISSUE TITLE
Failed to execute goal 'generateTests' while trying to generate contracts from an OpenApi yaml document

### ISSUE THREAD

**Issue by ingogriebsch** [corunet/scc-multiapi-converter#71]
Hello,

I would like to understand how this library works. So I created a Spring-Boot project based on Spring-Boot 2.7.3 and Spring-Cloud 2021.0.3. As build tool I use Maven 3.8 and to configure the project properly I followed the instructions on your website. As API definition I used the OpenApi [example](https://github.com/corunet/scc-multiapi-converter#%EF%B8%8F-writing-ymls) from your website.

When I run the build I get the following error message:

```
Failed to execute goal org.springframework.cloud:spring-cloud-contract-maven-plugin:3.1.3:generateTests (default-generateTests) on project openapi-scc: Execution default-generateTests of goal org. springframework.cloud:spring-cloud-contract-maven-plugin:3.1.3:generateTests failed: Failed to convert file [C:\opt\ws\work\_openapi-scc\src\main\resources\api\openapi.yml]: Cannot invoke "io.swagger.v3.oas.models.media.Schema.getExample()" because "schema" is null -> [Help 1].
```

Am I doing something wrong? Is the example missing some things? Is the library having a bug?

The project where I had the problem can be found here:
https://github.com/ingogriebsch/_openapi-scc

**Comment by IsaUlloa** [comment]
Hi @ingogriebsch ,

You can now check the changes we have made in this [branch](https://github.com/corunet/scc-multiapi-converter/tree/71-failed-to-execute-goal-generatetests-while-trying-to-generate-contracts-from-an-openapi-yaml-document).

Cheers.
